baseURL = 'https://cogitovirus.com/'
languageCode = 'en-us'
title = 'cogitovirus.com'

theme = 'cactus'

googleAnalytics = "UA-XXXXXXXX-XX"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[params]
  colortheme = "white"
  description = "This is a description"
  mainSection = "posts"
  mainSectionTitle = "Blog"
  showAllPostsOnHomePage = false
  postsOnHomePage = 5
  showProjectsList = false
  [params.comments]
    enabled = false

[[params.social]]
  name = "linkedin"
  link = "https://www.linkedin.com/in/cogitovirus/"

[[params.social]]
  name = "github"
  link = "https://github.com/cogitovirus/"

[[params.social]]
  name = "twitter"
  link = "https://twitter.com/cogitovirus3"

