baseURL = 'https://cogitovirus.com/'
languageCode = 'en-us'
title = 'cogitovirus.com'

theme = 'cactus'

enableRobotsTXT = true

[sitemap]
  filename = 'sitemap.xml'

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[params]
  colortheme = "classic"
  GoogleAnalyticsID = "G-F6QNNGB76R"
  keywords = ["personal website", "quality", "data engineering", "engineering", "AI", "data science"]
  description = "A personal site exploring engineering, software, and the future of technology, from algorithms to autonomy."
  mainSection = "posts"
  mainSectionTitle = "Blog"
  showAllPostsOnHomePage = false
  postsOnHomePage = 5
  showProjectsList = false
  showReadTime = true
  rss = true


[[params.social]]
  name = "twitter"
  link = "https://x.com/cogitovirus3"

[[params.social]]
  name = "github"
  link = "https://github.com/cogitovirus/"


[[params.social]]
  name = "email"
  link = "w.zolnierowicz@gmail.com"



