baseURL = 'https://cogitovirus.com/'
languageCode = 'en-us'
title = 'cogitovirus.com'

theme = 'cactus'

googleAnalytics = "G-F6QNNGB76R"
enableRobotsTXT = true

[sitemap]
  filename = 'sitemap.xml'

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[params]
  colortheme = "classic"
  description = "A personal website about work, engineering and stuff."
  mainSection = "posts"
  mainSectionTitle = "Blog"
  showAllPostsOnHomePage = false
  postsOnHomePage = 5
  showProjectsList = true

[[params.social]]
  name = "linkedin"
  link = "https://www.linkedin.com/in/cogitovirus/"

[[params.social]]
  name = "twitter"
  link = "https://twitter.com/cogitovirus3"

[[params.social]]
  name = "github"
  link = "https://github.com/cogitovirus/"



